### PR TITLE
chore: fix snapshot bot

### PR DESCRIPTION
**Pull request by StoneDot**
*Issue #, if available:*
Currently, the snapshot bot does not work correctly.
https://github.com/awslabs/dynein/actions/runs/6730473189.

*Description of changes:*
This pull request will fix the failure to generate a snapshot. Due to permission restriction, the bot only generates a diff. It means that the application of patches becomes the duty of requesters of pull requests.

The following is the example behavior of the bot.
https://github.com/StoneDot/dynein/pull/17#issuecomment-1794211433

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wafuwafu13** [comment]
https://github.com/awslabs/dynein/#bot should be updated

>If you want to update snapshots of commands, you can use bot command /snapshot in your pull request. Please note that you must type exactly as written.

bot can't update file now

**Comment by wafuwafu13** [comment]
I'm trying to figure out why we need this bot

- We can check the diff from test log [like this](https://github.com/StoneDot/dynein/actions/runs/6767501249/job/18390236950?pr=17#step:8:107)
- We can update snapshot by command 
https://github.com/awslabs/dynein#development

**Review by wafuwafu13 — CHANGES_REQUESTED** [review]
If we leave this bot, we would have to change the README.md description

**Comment by StoneDot** [comment]
The bot was introduced because some contributors may not have a Windows environment or a Linux environment. I believe this feature is still helpful for those who do not have an environment to create a snapshot. Manually changing the snapshot is error-prone and dull work. Generated the diff file mitigates this pain.

**Comment by StoneDot** [comment]
I have updated the documents and described the needs of the bot. Could you please check it again?

**Review by wafuwafu13 — APPROVED** [review]
LGTM

**Pull request merged**
