### PR TITLE
Update dependencies and toolchain to pass tests on aarch64-apple-darwin

### PR DESCRIPTION
**Pull request by StoneDot**
*Issue #, if available:*

Add support for aarch64-apple-darwin.

*Description of changes:*

* Update toolchain version to compile for aarch64-apple-darwin.
* Update dialogue to pass tests on aarch64-apple-darwin.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by thash — CHANGES_REQUESTED** [review]
Thank you for submitting the pull request. The toolchain `1.47.0` was unnecessary old, thus it would be a valuable change.

The change itself looks good to me, but I noticed that updating the toolchain may lead to failure on CI in GitHub actions. As the PR changes toolchain in `.github/workflows/ci.yml`, cargo fmt and clippy with the new toolchain will generate warnings that didn't exist with the previous toolchain.


- Before change:

```
$ git show --oneline
ed9098a (HEAD) Merge pull request #16 from thash/fix_ci
$ rustup show active-toolchain
1.47.0-x86_64-apple-darwin (overridden by '/Users/thash/ghq/github.com/awslabs/dynein/rust-toolchain')
$ cargo fmt --version
rustfmt 1.4.20-stable (48f6c32e 2020-08-09)
$ cargo clippy --version
clippy 0.0.212 (18bf6b4f0 2020-10-07)

$ cargo fmt --all -- --check
$ echo $?
0

$ cargo clippy -- -D warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
$ echo $?
0
```


- After change:

```
$ git checkout StoneDot/update-dep-and-toolchains-for-aarch64-apple-darwin
Previous HEAD position was ed9098a Merge pull request #16 from thash/fix_ci
HEAD is now at 00c2b37 Update CI toolchain version

$ rustup show active-toolchain
1.56.1-x86_64-apple-darwin (overridden by '/Users/thash/ghq/github.com/awslabs/dynein/rust-toolchain')
$ cargo fmt --version
rustfmt 1.4.37-stable (59eed8a2 2021-11-01)
$ cargo clippy --version
clippy 0.1.56 (59eed8a2 2021-11-01)

$ cargo fmt --all -- --check
... (snip) ...
Diff in /Users/thash/ghq/github.com/awslabs/dynein/src/data.rs at line 73:
 impl fmt::Display for DyneinQueryParamsError {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         match &self {
-        DyneinQueryParamsError::NoSuchIndex(idx, t) => {
-            write!(f, "No index named '{}' found on the target table '{}'. Please execute 'dy desc' command to see indexes the table has.", idx, t)
-        },
... (snip) ...
$ echo $?
1

$ cargo clippy -- -D warnings
... (snip) ...
warning: `dynein` (bin "dy") generated 2 warnings
error: could not compile `dynein` due to 33 previous errors; 2 warnings emitted
$ echo $?
101
```

How about fixing them in this PR in advance of the subsequent CI errors caused by the changes?

**Comment by StoneDot** [comment]
Thank you for your feedback. I'll fix it.

**Comment by StoneDot** [comment]
I rebase the commit before fix to prevent conflict.

**Comment by StoneDot** [comment]
Some fix like "GSI → Gsi" introduce incompatibility cache.yml. We need to delete old cache like `rm ~/.dynein/cache.yml`. We should note this on changelog.

**Comment by thash** [comment]
Thanks for the updates, now it's LGTM.
As you mentioned I needed to remove files under `~/.dynein/`; we will mention it in the next release note.

**Pull request merged**
