### PR TITLE
Make all output stable by sorting attributes

### PR DESCRIPTION
**Pull request by mlafeldt**
*Description of changes:*

With this change, all JSON, YAML, and raw output will be sorted by attribute keys. Making the output stable provides benefits like being able to diff exports/scans/etc and confusing users less. :)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mlafeldt** [comment]
@StoneDot @itazur PTAL

**Comment by StoneDot** [comment]
Thank you for your pull request and I apologize the delay of review.
I've discuss this PR with itazur. We concludes this pull request should be reviewed by design perspective because of potential backward incompatibility. We hope you give us additional time to review this PR.

**Comment by mlafeldt** [comment]
@StoneDot Sounds good. Looking forward to your decision.

In my opinion, making the output stable only means that people can expect it to be stable now, whereas they couldn't make any such assumption before.

**Comment by StoneDot** [comment]
@mlafeldt Thank you for your patience. We want to merge this PR with some modifications.

Required modifications are the following:
* Add an option to specify ordering like `--sortedjson` for this PR.
* Original behaviors of `output` options should be held.
* Ensure the ordering of [List](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes.Document.List) by test. But if you feel this requires too much work, you can create the issue for future work.

I believe the above modification demands a little effort, but please let me know if you need assistance to implement it.

I want to write down the decision background.
First, the incompatibility introduced by this change can be acceptable for us because dynein is still in an early stage of development. But another consideration point exists. DynamoDB does not provide any guarantee for attribute ordering. Thus, we don't want to impress that the native DynamoDB delivers a guarantee for attribute ordering. This is the reason we decide to add an option for ordering attributes.

If you have any questions regarding the above decision, please comment.

**Comment by wafuwafu13** [comment]
We will close this issue.

> DynamoDB does not provide any guarantee for attribute ordering. Thus, we don't want to impress that the native DynamoDB delivers a guarantee for attribute ordering.

dynein doesn't deliver a guarantee for attribute ordering:

```zsh
$ dy get 1958 "Touch of Evil" --region eu-west-1 --table Movie   
{
  "title": "Touch of Evil",
  "info": {
    "actors": [
      "Charlton Heston",
      "Janet Leigh",
      "Orson Welles"
    ],
    (snip)
  },
  "year": 1958
}

$ dy get 1958 "Touch of Evil" --region eu-west-1 --table Movie
{
  "title": "Touch of Evil",
  "year": 1958,
  "info": {
    "actors": [
      "Charlton Heston",
      "Janet Leigh",
      "Orson Welles"
    ],
    (snip)
  }
}
```

Instead, we can use `jq -S` to sort result:

```zsh
$ dy get 1958 "Touch of Evil" --region eu-west-1 --table Movie | jq -S
{
  "info": {
    "actors": [
      "Charlton Heston",
      "Janet Leigh",
      "Orson Welles"
    ],
    (snip)
  },
  "title": "Touch of Evil",
  "year": 1958
}
```

**Comment by mlafeldt** [comment]
Alright.

**Pull request closed without merging**
